name: Deploy Stein Invest Dashboard

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload website via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Repository ophalen
        uses: actions/checkout@v6

      - name: Upload to server
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /
          timeout: 60000
          log-level: verbose
